AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketPipelineLogs:
    Type: String

Resources:
  BucketForPipelineLogs:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketPipelineLogs
      VersioningConfiguration:
        Status: Suspended
      LifecycleConfiguration:
        Rules:
          - Id: DeleteRule
            Status: Enabled
            ExpirationInDays: 30
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256