AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DynamoFormatMetadataName:
    Type: String
  DynamoFormatMetadataKey:
    Type: String

  DynamoDataQualityName:
    Type: String
  DynamoDataQualityKey:
    Type: String
    
  DynamoFormatChangesMetadataName:
    Type: String
  DynamoFormatChangesMetadataKey:
    Type: String

Resources:
  DynamoFormatMetadata:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoFormatMetadataName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: !Ref DynamoFormatMetadataKey
        AttributeType: S
      KeySchema:
      - AttributeName: !Ref DynamoFormatMetadataKey
        KeyType: HASH
      SSESpecification:
        SSEEnabled: true  

  DynamoDataQualityMetadata:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDataQualityName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: !Ref DynamoDataQualityKey
        AttributeType: S
      KeySchema:
      - AttributeName: !Ref DynamoDataQualityKey
        KeyType: HASH
      SSESpecification:
        SSEEnabled: true  

  DynamoFormatChangesMetadata:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoFormatChangesMetadataName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: !Ref DynamoFormatChangesMetadataKey
        AttributeType: S
      KeySchema:
      - AttributeName: !Ref DynamoFormatChangesMetadataKey
        KeyType: HASH
      SSESpecification:
        SSEEnabled: true  