AWSTemplateFormatVersion: '2010-09-09'

Description: 'AWS CloudFormation template to create monitoring and observability resources
              for Hybrid Data Architecture project. The main Idea with this template is create
              the aws resources that we need to catch possible errors in hour dat apipelines'

Parameters:
  DynamoFormatMetadataName:
    Description: 'Table name for data formats table'
    Type: String
    Default: format_metadata_logs
  DynamoFormatMetadataKey:
    Description: "key for data format table"
    Type: String
    Default: pipeline
  
  DynamoDataQualityName:
    Description: 'Table name for data quality at load phase'
    Type: String
    Default: pipeline_excecution_logs
  DynamoDataQualityKey:
    Description: 'key for data quality at load phase'
    Type: String
    Default: pipeline
  
  DynamoFormatChangesMetadataName:
    Description: 'Table name for format changes table'
    Type: String
    Default: format_changes_logs
  DynamoFormatChangesMetadataKey:
    Description: 'key for format changes table'
    Type: String
    Default: pipeline


  PipelineLogGroupName:
    Description: 'Log group name for monitoring logs in cloudwatch'
    Type: String
    Default: monitoring-pipelines
  ExtractLogStreamName:
    Description: 'logstream for any extract error'
    Type: String
    Default: Extract
  TransformLogStreamName:
    Description: 'logstream for any transform error'
    Type: String
    Default: Transform
  LoadLogStreamName:
    Description: 'logstream for any load error'
    Type: String
    Default: Load
  ResultLogStreamName:
    Description: 'logstream for pipeline result summary'
    Type: String
    Default: Results
  
Resources:
  dynamo:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://observability-diego-dsi.s3.amazonaws.com/dynamo.yaml
      Parameters:
        DynamoFormatMetadataName: !Ref DynamoFormatMetadataName
        DynamoFormatMetadataKey: !Ref DynamoFormatMetadataKey
        DynamoDataQualityName: !Ref DynamoDataQualityName
        DynamoDataQualityKey: !Ref DynamoDataQualityKey
        DynamoFormatChangesMetadataName: !Ref DynamoFormatChangesMetadataName
        DynamoFormatChangesMetadataKey: !Ref DynamoFormatChangesMetadataKey

  cloudwatch:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://observability-diego-dsi.s3.amazonaws.com/cloudwatch.yaml
      Parameters:
        PipelineLogGroupName: !Ref PipelineLogGroupName
        ExtractLogStreamName: !Ref ExtractLogStreamName
        TransformLogStreamName: !Ref TransformLogStreamName
        LoadLogStreamName: !Ref LoadLogStreamName
        ResultLogStreamName: !Ref ResultLogStreamName